sbatch run_noiseless_Peaks.sh
sbatch run_noisy_PS_2000.sh
sbatch run_ngal40_Peaks.sh
sbatch run_noiseless_PS.sh
sbatch run_noisy_PS_8000.sh
sbatch run_ngal40_PS.sh
sbatch run_noisy_Peaks.sh
sbatch run_noisy_PS.sh
sbatch run_noisy_Peaks_nr2000.sh
sbatch run_noisy_Peaks_nr5000.sh
sbatch run_noisy_PS_nr2000.sh
sbatch run_noisy_PS_nr5000.sh
